const UserActionTypes = {
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_TOKEN: 'SIGN_IN_TOKEN', 
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SEND_MESSAGE_START: 'SEND_MESSAGE_START',
    SENDING_MESSAGE_STATUS: 'SENDING_MESSAGE_STATUS',
    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    SEND_DISCUSSION_MESSAGE: 'SEND_DISCUSSION_MESSAGE',
    SENDING_DISCUSSION_MESSAGE_STATUS: 'SENDING_DISCUSSION_MESSAGE_STATUS',
    REFRESH_USER: 'REFRESH_USER',
    SEND_REPLY: 'SEND_REPLY',
    SENDING_REPLY_STATUS: 'SENDING_REPLY_STATUS',
    FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
    TOGGLE_USER_HEADER_OPTIONS_DISPLAY: 'TOGGLE_USER_HEADER_OPTIONS_DISPLAY', 
    LIKING_POST:'LIKING_POST'
}

export default UserActionTypes;